name: env-cwms
channels:
  - conda-forge
  - defaults
dependencies:
   - python=3.9.18
   - beautifulsoup4=4.12.3
   - bokeh=3.3.4
   - certifi=2024.2.2
   - charset-normalizer=3.3.2
   - contourpy=1.2.0
   - cx_Oracle=8.3.0
   - cycler=0.12.1
   - fonttools=4.49.0
   - idna=3.6
   - importlib_resources=6.1.2
   - Jinja2=3.1.3
   - kiwisolver=1.4.5
   - MarkupSafe=2.1.5
   - matplotlib=3.8.3
   - numpy=1.26.4
   - packaging=23.2
   - pandas=2.1.3
   - pillow=10.2.0
   - pyparsing=3.1.1
   - python-dateutil=2.8.2
   - python-dotenv=1.0.1
   - pytz=2024.1
   - PyYAML=6.0.1
   - requests=2.31.0
   - requests-toolbelt=1.0.0
   - seaborn=0.13.2
   - six=1.16.0
   - soupsieve=2.5
   - tornado=6.3.2
   - urllib3=2.2.1
   - xarray=2024.2.0
   - xyzservices=2023.10.1
   - zipp=3.17.0
   - jupyterlab=4.2.3
